version: '2.12'

services:
  api:
    build:
      context: .
    container_name: 
    working_dir: ./
    restart: unless-stopped
    ports:
      - '3000:3000'

    volumes:
      - ./:/dockerLab1
      - /dockerLab1/node_modules
