version: '2.12'

services:
 
  api:
    build:
      context: .
    container_name: labDocker
    working_dir: /app
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
    - POSTGRES_PASSWORD=root
    - POSTGRES_USER=postgres
    image: postgres:15.1
    volumes:
      - ./app:/app
      - /app/node_modules
